### PR TITLE
Boost multiprecision

### LINKED ISSUE #617: Quadruple precision support is broken
I added --enable-quadrupleprecision after noticing that PETSc had dropped support for long double and added support for __float128, but I've never tried it until today.

It doesn't work.  Including cmath only declares e.g. std::sqrt() for float, double, and long double, not for __float128.  Anything trying to do sqrt(someLibmeshReal) fails to compile.

The only obvious fix I see is to create a libmesh_cmath.h shim which includes quadmath.h and defines all the overloads e.g. `std::sqrt(__float128 foo) { return sqrtq(foo); }`  We then replace inclusion of cmath with inclusion of libmesh_cmath.h throughout the library.

That's a bit invasive.  Anyone have any better ideas?

### PR DESCRIPTION
**Pull request by roystgnr**
Sorry this is so huge; it turned out to be much more work than I anticipated when, a couple months ago, I thought "I should work on some old tickets in the down time between juggling other tasks".

I'm in no great hurry to merge it if anyone has the desire to review it but not the time, or if anyone finds problems or has disagreements.  It fixes #617 and has a number of more general improvements, but it's been a work in progress for a while and it's not urgent.

### CODE REVIEW

**Comment by jwpeterson** [comment]
tenor

File: tests/quadrature/quadrature_test.C [hunk 1]
```diff
@@ -511,6 +515,10 @@ public:
   template <QuadratureType qtype, Order order, unsigned int exactorder>
   void test3DWeights ()
   {
+    // Our Gauss-Lobatto rules are only computed to double precision
```
Comment (jwpeterson) [inline tests/quadrature/quadrature_test.C]: Wait, why? They should have like 32 *accurate* decimal digits.

Comment (roystgnr) [reply tests/quadrature/quadrature_test.C]: We've got a bunch of 32 decimal place literals, but they're all suffixed with L, which truncates to 20 digits when it interprets them as long double.  If we really want all the precision we can get, we'll need a new suffix that we can shim to the boost suffix when we have it or to L when we don't.

Since those unit tests use ```TOLERANCE*sqrt(TOLERANCE)``` and I only set ```TOLERANCE = 1e-11```, 20 digits was good enough for most cases.  But we don't have 20 digits everywhere.

For Gaussian quadrature on Tets we only have 15 digits at second order:
https://github.com/libMesh/libmesh/blob/17be2c62003504c8555d7af2400fc7fd2d5e5924/src/quadrature/quadrature_gauss_3D.C#L85
and likewise on Triangles at seventh order:
https://github.com/libMesh/libmesh/blob/17be2c62003504c8555d7af2400fc7fd2d5e5924/src/quadrature/quadrature_gauss_2D.C#L338

And... what the hell.  I could swear that I saw a similar case in the Gauss-Lobatto rules, and that that prompted me to rule out those specific unit tests, but now I can't find it.  Let me reenable them and see what happens.

Comment (roystgnr) [reply tests/quadrature/quadrature_test.C]: I do get failures again.  In both 2D and 3D, for both ```SIXTH``` and ```SEVENTH``` order.

OH HELL.  There's a ```0.1``` in gauss_lobatto_quadrature_1D.C I need to change to ```1/Real(10)```, isn't there?

Comment (roystgnr) [reply tests/quadrature/quadrature_test.C]: And that fixes the tests for me.  I'll upload in a minute.

Comment (roystgnr) [reply tests/quadrature/quadrature_test.C]: Thanks for catching this!!

Comment (jwpeterson) [reply tests/quadrature/quadrature_test.C]: > Thanks for catching this!!

Sure, but I think you are the one who caught the but that I apparently left as an easter egg in 3998bf26f.

Comment (jwpeterson) [reply tests/quadrature/quadrature_test.C]: > If we really want all the precision we can get, we'll need a new suffix that we can shim to the boost suffix when we have it or to L when we don't.

I scanned the boost.multiprecision introduction and "Literal types support" docs. It looks like only the only supported user-defined literals are currently `_cppi`, `_cppui`, etc. which are all for integral types. 

According to [this](https://stackoverflow.com/questions/33043809/what-is-the-precision-of-cpp-dec-float-50) it looks like you can pass a string to e.g. the `boost::multiprecision::cpp_dec_float_50` constructor. Maybe it's possible to come up with a simple `to_real()` macro that would do the right thing (stringification, concatenation, etc.) in all cases from the same input?

```C
#ifdef LIBMESH_DEFAULT_QUAD_PRECISION
#define to_real(x) boost::multiprecision::cpp_dec_float_50("#x")
#else
#define to_real(x) long double(x##L)
#endif
```
```
_weights[0] = to_real(6.6666666666666666666666666666667e-02);
```

**Comment by jwpeterson** [comment]
This PR also reminds me that we are still on Boost 1.61 (May 2016) internally. Not suggesting we should also update that in *this* PR, but they are up to version 1.70 now.

File: tests/quadrature/quadrature_test.C (hunk 1 above)
Comment (roystgnr) [reply tests/quadrature/quadrature_test.C]: Just doing stringification in a macro seems clever.  I'd just been *assuming* that we needed to use user-defined literals, but I guess as long as the cpp_dec_float constructor and the conversion to float128 are both constexpr then it'll work out just fine in the end.

**Comment by roystgnr** [comment]
Not a bad idea.  If we do that eventually though then we might as well do the user defined literal thing; IIRC 1.70 is where I noticed they had the Q suffix defined.

**Comment by roystgnr** [comment]
Oh, good boy Civet.  I hadn't thought to do "make installcheck" or to try a complex build, and although I had been testing without MPI it looks like I didn't repeat that build after my final changes to the parallel headers.

**Comment by roystgnr** [comment]
I'm going to avoid doing any interactive rebasing, just toss fix commits on the end, for fear of screwing up any reviewing in progress, but I can do a final reorders+fixups cleanup on the commit history after the final state is in a happy place.

**Comment by roystgnr** [comment]
Throwing on some more tests for compiler variations, downstream apps, valgrind etc.

**Comment by roystgnr** [comment]
Those seem to be unrelated failures.  Looks like the default tests are currently on PETSc 3.10.5, but the tests with old gcc+clang are using PETSc 3.7.6, and the latter doesn't support one of the command line options that @bboutkov used this spring in a new fem_system_ex1 test in #2151.

The PETSc documentation suggests that PCMGSetGalerkin was added in PETSc 3.8, so we can just test for that and skip those last couple tests if we have something older.  While we're at it we probably ought to be skipping the earlier petsc option tests in cases where we don't have PETSc at all.

**Comment by roystgnr** [comment]
Hopefully I didn't screw up the conflict resolution.

After exchanging IMs with @jwpeterson I'm going to feel free to start doing fixups and merge (or merges, if I split some more logically independent parts into separate PRs) soon.

**Comment by roystgnr** [comment]
Okay: everything that has value outside the extended precision context has been split out and merged, and for the handful of ugly ```Point(Real(scalar))``` commits I was dubious about I found a better solution and got rid of them, so the rest I'll merge all in one batch sometime this weekend after confirming that both CI and my own tests are still happy.
