### PR TITLE
Fix a bug on allocating segmentlist in Triangle interface

### LINKED ISSUE #2339: A bug in Triangle interface
If both segments and holes are given, currently the interface does not allocate the segment list in a proper size. The offending line is at https://github.com/libMesh/libmesh/blob/master/src/mesh/mesh_triangle_interface.C#L138. I will send in a quick fix.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #2339.

I cannot find a unit test for the interface so I did not try to add any test. But I did verify that this fixes the problem.

### CODE REVIEW

File: src/mesh/mesh_triangle_interface.C [hunk 1]
```diff
@@ -106,13 +106,18 @@ void TriangleInterface::triangulate()
...
   unsigned int n_hole_points = 0;
+  unsigned int num_hole_segments = 0;
 
   if (have_holes)
     for (const auto & hole : *_holes)
+    {
       n_hole_points += hole->n_points();
+      for (unsigned int i=0; i<hole->segment_indices().size()-1; ++i)
+        num_hole_segments += hole->segment_indices()[i+1] - hole->segment_indices()[i];
+    }
```
Comment (jwpeterson) [inline src/mesh/mesh_triangle_interface.C]: It appears that `segment_indices()` function always returns a vector with exactly 2 entries? And even if it didn't this loop would add/subtract the intermediate values anyway so you would only end up with the difference between the first and last entry. Not saying this is wrong, just trying to understand what's going on.

Comment (YaqiWang) [reply src/mesh/mesh_triangle_interface.C]: Yes, the size of `segment_indices()` is `n`+1, where `n` is the number of segments described by nodes on the segments.

Comment (YaqiWang) [reply src/mesh/mesh_triangle_interface.C]: For example of a hole created by two concentric circles in the ring. In such a case, `n` will be 2. The entries in `segment_indices()` will be 3. The nodes are ordered properly so that we can have implicit rule on adding segments with just these three numbers.

Comment (YaqiWang) [reply src/mesh/mesh_triangle_interface.C]: I will add an assertion to make sure we have a peaceful mind ;-)

Comment (jwpeterson) [reply src/mesh/mesh_triangle_interface.C]: What I'm saying is, if segment_indices = [a,b,c,d,..., z] then the result of your calculation above is simply `num_hole_segments` = z-a because all the intermediate terms cancel. So there's no reason to do this loop?

Comment (YaqiWang) [reply src/mesh/mesh_triangle_interface.C]: Yes, I think we just need to fix Line 138.

**Comment by YaqiWang** [comment]
@jwpeterson You are right. The fix should be just one line. I left the two assertions since that can possibly increase the readability of the code and assure the correctness of hole generation.
