### PR TITLE
Fix --disable-amr builds

### LINKED ISSUE #850: Build fails with --disable-amr
There are issues with systems/fem_context.C, maybe other files too.

### PR DESCRIPTION
**Pull request by roystgnr**
This resolves #850.  Again.  Probably temporarily again.

### CODE REVIEW

File: src/geom/elem.C [hunk 1]
```diff
@@ -1171,7 +1171,7 @@ void Elem::remove_links_to_me()
 #else
               unsigned int my_s = neigh->which_neighbor_am_i(this);
               libmesh_assert_less (my_s, neigh->n_neighbors());
-              libmesh_assert_equal_to (neigh->neighbor(my_s), this);
+              libmesh_assert_equal_to (neigh->neighbor_ptr(my_s), this);
```
Comment (jwpeterson) [inline src/geom/elem.C]: Ha, I thought we had found all these!
